### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by avijitnagare** [nicktoumpelis/HiBeacons#14]
I am not getting UUID. How to get UUID ?

 let region = CLBeaconRegion(proximityUUID: NSUUID(UUIDString: "?")!, identifier: "Identifier")

**Comment by nicktoumpelis** [comment]
@avijitnagare You need to figure out what the UUID of your beacons should be. That depends on your manufacturer, etc. You should replace the default value I use, with the UUID of your own beacons.
