### ISSUE TITLE
How the advertising and monitoring will work ?

### ISSUE THREAD

**Issue by poonamdhomane** [nicktoumpelis/HiBeacons#19]
I run the sample. i can see the on Ranging enable ,the beacons in range.
But for first two switches they are just loading and loading

**Comment by nicktoumpelis** [comment]
Advertising means that the app is transmitting its iBeacon information nearby. You should not expect to see anything on the instance of the app. If you have another app running nearby (with the same UUID), you should be able to see it. Monitoring works mostly when you enter and exit a beacon range, and it will post a notification upon such an event. However, most beacons have a large range these days so you should be quite far away to start triggering these events (> 10 m).

I would say, however, that you should first make sure that the app has the correct UUID, and not the default one I set when I created the project. 

Thanks!
