### ISSUE TITLE
Beacons don't show up

### ISSUE THREAD

**Issue by besi** [nicktoumpelis/HiBeacons#20]
### Setup

I want to build an audio guide application on iOS for an exhibition using iBeacons.

I am using the [HiBeacons App](https://github.com/nicktoumpelis/HiBeacons) from Github to test my iBeacons:

[![app][1]][1]

This works well and I can configure my iPad to show up as an iBeacon. So I can already start developing using my iPad as a dummy beacon.

### The iBeacons

[![beacons][2]][2]

I did order a few [iBeacons from Aliexpress](https://www.aliexpress.com/item/Wholesale-Nordic-NRF51822-Bluetooth-4-0-Beacon-BLE-holyiot-iBeacon-proximity-marketing/32790922059.html). 

I was expecting that the beacons show up in HiBeacons as soon as I turn them on. And when I press the button for some seconds the LED lights up either once or three times, but in both states the HiBeacons app does not show a new nearby device.

The Beacons all come with a label that shows the following information:

    major: 10011
    minor: 10011
    wxid: 2976871
    password: XXXXXXXX
    ID: YYYYYYYYYYYYY

There is also a QR Code that contains the ID of the beacon. 

Now I am left with these questions:

1. What do I need to do so that the beacons show up in HiBeacon
2. Are the wxid / password proprietary values or is this part of BLE spec

  [1]: https://i.stack.imgur.com/Wc3dn.png
  [2]: https://i.stack.imgur.com/xxUcc.jpg

**Comment by nicktoumpelis** [comment]
@besi can you provide any additional info?

**Comment by besi** [comment]
@nicktoumpelis: Sorry Nick, I was filing an issue but then was not sure if I should post it at all, since it is a more broad question on the topic. However, I did add the information now. Please feel free to close the issue if it's too off-topic.

**Comment by nicktoumpelis** [comment]
@besi The ID printed at the bottom of the beacons is not a UUID. I believe that you have to specifically enable iBeacon advertising through some configuration utility; the seller page you linked at points to an app called "LightBlue". Then you can scan for whatever UUID you choose in the configuration utility.

I'm sorry I can't be of more help.

**Comment by besi** [comment]
Thank you very much for your help. Ill give that a shot.
